version: "3.8"
services:
  app:
    build:
      args:
        user: ec2-user
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: thedoorstop
    container_name: thedoorstop-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - thedoorstop
  db:
    image: mysql:8.1
    container_name: thedoorstop-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      SERVICE_TAGS: prod
      SERVICE_NAME: mysql
    volumes:
      - ./docker-compose/mysql:/data/db
    networks:
      - thedoorstop
  nginx:
    image: nginx:1.25-alpine
    container_name: thedoorstop-nginx
    restart: unless-stopped
    ports:
      - 80:80
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d
    networks:
      - thedoorstop

networks:
  thedoorstop:
    driver: bridge