version: "3.8"

volumes:
  db-data:

services:
  app:
    build:
      args:
        user: ec2-user
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: thedoorstop
    container_name: thedoorstop-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - thedoorstop
  db:
    image: mysql:8.1
    container_name: thedoorstop-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_TCP_PORT: 3306
      SERVICE_TAGS: prod
      SERVICE_NAME: mysql
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - thedoorstop
  nginx:
    image: nginx:1.25-alpine
    container_name: thedoorstop-nginx
    restart: unless-stopped
    ports:
      - 80:80
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d
    networks:
      - thedoorstop
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: thedoorstop-pma
    restart: unless-stopped
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    ports:
      - 8080:80
    links:
      - db
    networks:
      - thedoorstop
    depends_on:
      - db
networks:
  thedoorstop:
    driver: bridge
